/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas2;

import ControladorCliente.CitasDao;
import ControladorCliente.ClienteDao;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.EntidadCita;
import modelo.EntidadCliente;
import modelo.EntidadTipoCons;

/**
 *
 * @author moisesvelasco
 */
public class Clientes extends javax.swing.JInternalFrame {

    ClienteDao dao = new ClienteDao();
    EntidadCliente ec = new EntidadCliente();
    EntidadCita entC = new EntidadCita();
    CitasDao cDao= new CitasDao();
    DefaultTableModel modeloCliente = new DefaultTableModel();
    DefaultTableModel modeloCitas = new DefaultTableModel();
    int id;
    public Clientes() {
        initComponents();
        listarCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        escrito = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        contacto = new javax.swing.JRadioButton();
        idC = new javax.swing.JRadioButton();
        nombre = new javax.swing.JRadioButton();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Eliminar = new javax.swing.JButton();
        btnVerCitas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCitas = new javax.swing.JTable();
        btnVerReg = new javax.swing.JButton();
        listar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        Eliminar1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        escrito.setLayout(null);

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre del paciente", "Domicilio", "Telefono", "Fecha de registro", "inicia ", "termina", "Edad", "Sexo"
            }
        ));
        tablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCliente);
        if (tablaCliente.getColumnModel().getColumnCount() > 0) {
            tablaCliente.getColumnModel().getColumn(0).setMaxWidth(60);
            tablaCliente.getColumnModel().getColumn(1).setMaxWidth(430);
            tablaCliente.getColumnModel().getColumn(2).setMaxWidth(430);
            tablaCliente.getColumnModel().getColumn(3).setMaxWidth(130);
            tablaCliente.getColumnModel().getColumn(4).setMaxWidth(170);
            tablaCliente.getColumnModel().getColumn(5).setMaxWidth(170);
            tablaCliente.getColumnModel().getColumn(6).setMaxWidth(170);
            tablaCliente.getColumnModel().getColumn(7).setMaxWidth(60);
            tablaCliente.getColumnModel().getColumn(8).setMaxWidth(90);
        }

        escrito.add(jScrollPane1);
        jScrollPane1.setBounds(10, 260, 1200, 320);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Marion", 1, 16)); // NOI18N
        jLabel1.setText("BUSCAR POR :");

        buttonGroup1.add(contacto);
        contacto.setText("CONTACTO");

        buttonGroup1.add(idC);
        idC.setText("ID CLIENTE");

        buttonGroup1.add(nombre);
        nombre.setText("NOMBRE");

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(contacto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contacto)
                            .addComponent(idC)
                            .addComponent(nombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        escrito.add(jPanel1);
        jPanel1.setBounds(10, 20, 464, 110);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        Eliminar.setBackground(new java.awt.Color(255, 51, 51));
        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setText("ELIMINAR");
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
        });

        btnVerCitas.setBackground(new java.awt.Color(153, 153, 255));
        btnVerCitas.setText("VER CITAS");
        btnVerCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCitasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Marion", 1, 16)); // NOI18N
        jLabel2.setText("ID DEL CLIENTE :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Eliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVerCitas))
                            .addComponent(jLabel2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar)
                    .addComponent(btnVerCitas))
                .addContainerGap())
        );

        escrito.add(jPanel2);
        jPanel2.setBounds(480, 20, 249, 109);

        tablaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "F O L I O.", "ID CLIENTE", "F E C H A.", "TIPO DE CONSULTA", "SALDO "
            }
        ));
        tablaCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCitasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaCitas);
        if (tablaCitas.getColumnModel().getColumnCount() > 0) {
            tablaCitas.getColumnModel().getColumn(0).setMaxWidth(90);
            tablaCitas.getColumnModel().getColumn(1).setMaxWidth(90);
            tablaCitas.getColumnModel().getColumn(4).setMaxWidth(70);
        }

        escrito.add(jScrollPane2);
        jScrollPane2.setBounds(760, 10, 454, 130);

        btnVerReg.setText("VER REGISTROS");
        btnVerReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRegActionPerformed(evt);
            }
        });
        escrito.add(btnVerReg);
        btnVerReg.setBounds(900, 170, 150, 29);

        listar.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        listar.setText("Listar");
        listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarActionPerformed(evt);
            }
        });
        escrito.add(listar);
        listar.setBounds(30, 140, 120, 29);

        jLabel3.setFont(new java.awt.Font("Marion", 1, 16)); // NOI18N
        jLabel3.setText("# F O L I O :");
        escrito.add(jLabel3);
        jLabel3.setBounds(640, 180, 100, 18);

        txtFolio.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 17)); // NOI18N
        escrito.add(txtFolio);
        txtFolio.setBounds(740, 170, 120, 31);

        Eliminar1.setBackground(new java.awt.Color(255, 51, 51));
        Eliminar1.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar1.setText("ELIMINAR");
        Eliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar1MouseClicked(evt);
            }
        });
        escrito.add(Eliminar1);
        Eliminar1.setBounds(1080, 180, 104, 29);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Boton para eliminar cita");
        escrito.add(jLabel4);
        jLabel4.setBounds(1060, 160, 160, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escrito, javax.swing.GroupLayout.PREFERRED_SIZE, 1228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(escrito, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void listarCliente(){
        try{
        List<EntidadCliente> lista =dao.listar();
        modeloCliente =(DefaultTableModel)tablaCliente.getModel();        
        Object[]ob = new Object[10];
        for(int i = 0;i<lista.size();i++){
            ob[0]=lista.get(i).getIdCliente();
            ob[1]=lista.get(i).getNombreCliente();
            ob[2]=lista.get(i).getDomicilio();
            ob[3]=lista.get(i).getContacto();
            ob[4]=lista.get(i).getFechaRegistro();
            ob[5]=lista.get(i).getFechaInicia();
            ob[6]=lista.get(i).getFechaTermina();
            ob[7]=lista.get(i).getEdad();
            ob[8]=lista.get(i).getSexo();
            
            modeloCliente.addRow(ob);
        }
        tablaCliente.setModel(modeloCliente);
        }
        catch(Exception e){ JOptionPane.showMessageDialog(this, "error en listar"+e.getMessage()); }
        
    }
    void buscar(){
        if(contacto.isSelected()==true){
        String contact=txtBuscar.getText();
        try{    
            EntidadCliente ec=dao.obtenerinfoContacto(contact);
            int idCLI=ec.getIdCliente();
            
            JOptionPane.showMessageDialog(this, "id"+idCLI);
        List<EntidadCliente> lista =dao.listarUnCliente(idCLI);       
        modeloCliente =(DefaultTableModel)tablaCliente.getModel();        
        Object[]ob = new Object[10];
        for(int i = 0;i<lista.size();i++){
            ob[0]=lista.get(i).getIdCliente();
            ob[1]=lista.get(i).getNombreCliente();
            ob[2]=lista.get(i).getDomicilio();
            ob[3]=lista.get(i).getContacto();
            ob[4]=lista.get(i).getFechaRegistro();
            ob[5]=lista.get(i).getFechaInicia();
            ob[6]=lista.get(i).getFechaTermina();
            ob[7]=lista.get(i).getEdad();
            ob[8]=lista.get(i).getSexo();
            
            modeloCliente.addRow(ob);
        }
        tablaCliente.setModel(modeloCliente);
        }
        catch(Exception e){ JOptionPane.showMessageDialog(this, "error en listar"+e.getMessage()); }
        }
    }
    void verCitas(){
        int tps;//tipo consulta
        EntidadTipoCons etp;
        String ntps;
        try{
            int id =Integer.parseInt(txtId.getText().toString());
        List<EntidadCita> lista =cDao.listarCitas(id);
        modeloCitas =(DefaultTableModel)tablaCitas.getModel();        
        Object[]ob = new Object[10];
        for(int i = 0;i<lista.size();i++){
            ob[0]=lista.get(i).getFolio();
            ob[1]=lista.get(i).getIdCliente();
            ob[2]=lista.get(i).getFechaCita();
             tps=lista.get(i).getTipoConsulta();
           
            etp=cDao.obtenerNomTipoCons(tps);
            ntps=etp.getNombreConsulta();
            ob[3]=ntps;
            ob[4]=lista.get(i).getSaldo();
            modeloCitas.addRow(ob);
        }
        tablaCitas.setModel(modeloCitas);
        }
        catch(Exception e){ JOptionPane.showMessageDialog(this, "error en listar citas Verifique que el id este en la casilla"+e.getMessage()); }
    }
     void centrarVentanas(JInternalFrame frame){
        escrito.add(frame);
        Dimension dimension=escrito.getSize();
        Dimension Dframe = frame.getSize();
        frame.setLocation((dimension.width -Dframe.height)/3,(dimension.height -Dframe.height)/3);
        frame.show();
    }
    
    
    void limpiarTabla(){
        for(int i = 0;i<modeloCliente.getRowCount();i++ ){
        modeloCliente.removeRow(i);
        i=i-1;
        }
    }
    void limpiarTablaCitas(){
        for(int i = 0;i<modeloCitas.getRowCount();i++ ){
        modeloCitas.removeRow(i);
        i=i-1;
        }
    }
    private void tablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClienteMouseClicked
        // TODO add your handling code here:
        int fila = tablaCliente.getSelectedRow();
        if(fila==-1){JOptionPane.showMessageDialog(this, "debe selecionar una fila"); }
        else{
            try {
                id = Integer.parseInt(tablaCliente.getValueAt(fila, 0).toString());
                
                txtId.setText(""+id);
            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_tablaClienteMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        limpiarTabla();
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarActionPerformed
        limpiarTabla();
        listarCliente();
    }//GEN-LAST:event_listarActionPerformed

    private void btnVerCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCitasActionPerformed
        limpiarTablaCitas();
        verCitas();
    }//GEN-LAST:event_btnVerCitasActionPerformed

    private void tablaCitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCitasMouseClicked
        int fila1 = tablaCitas.getSelectedRow();
        if(fila1==-1){JOptionPane.showMessageDialog(this, "debe selecionar una fila"); }
        else{
            try {
               int folio= Integer.parseInt(tablaCitas.getValueAt(fila1, 0).toString());
                
                txtFolio.setText(""+folio);
            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_tablaCitasMouseClicked

    private void btnVerRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRegActionPerformed
        if(txtFolio.getText().equals("")){JOptionPane.showMessageDialog(this, "la casilla del folio esta vacia selecciona una fila en la tabla de citas");}
        else{
        int folioC=Integer.parseInt(txtFolio.getText().toString());
        entC=cDao.obtenerDatosCita(folioC);//obtenemos el id del cliente por medio del folio que esta en txtFolio
        int idCl=entC.getIdCliente();//idCliente 
        JOptionPane.showMessageDialog(this, "idCl"+idCl);
        Cuentas cu = new Cuentas();
        cu.folio=folioC;
        cu.idCliente=idCl;
        cu.setVisible(true);
        dispose();
        dispose();
        }
    }//GEN-LAST:event_btnVerRegActionPerformed

    private void Eliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar1MouseClicked
        if(txtFolio.getText().equals("")){JOptionPane.showMessageDialog(this, "la casilla del folio esta vacia selecciona una fila en la tabla de citas");}
        else{
        int folioC=Integer.parseInt(txtFolio.getText().toString());
        EliminarCita ec = new EliminarCita();
        ec.folioElim=folioC;
            centrarVentanas(ec);
        }
    }//GEN-LAST:event_Eliminar1MouseClicked

    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseClicked
        if(txtId.getText().equals("")){JOptionPane.showMessageDialog(this, "Casilla ID CLIENTE esta vacia selecciona una fila en la tabla de CLIENTES");}
        else{
        int idc=Integer.parseInt(txtId.getText().toString());
        EliminarCita ec = new EliminarCita();
        ec.idCli=idc;
            centrarVentanas(ec);
        }
    }//GEN-LAST:event_EliminarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Eliminar1;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnVerCitas;
    private javax.swing.JButton btnVerReg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton contacto;
    private javax.swing.JDesktopPane escrito;
    private javax.swing.JRadioButton idC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton listar;
    private javax.swing.JRadioButton nombre;
    private javax.swing.JTable tablaCitas;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
