/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas2;

import ControladorCliente.CitasDao;
import ControladorCliente.ClienteDao;
import javax.swing.JOptionPane;

/**
 *
 * @author moisesvelasco
 */
public class EliminarCita extends javax.swing.JInternalFrame {

    CitasDao cDao= new CitasDao();
    ClienteDao dao = new ClienteDao();
    int folioElim;
    int idCli;
    public EliminarCita() {
        initComponents();
        identificar();
    }
    //resivir el id o folio y identifacarlo
    void identificar(){
        if(folioElim!=0){lbIndicador.setText("FOLIO DE CITA: ");}
        if(idCli!=0){lbIndicador.setText("ID CLIENTE: ");}
    }
    void eliminarCita(){
        if(txtFolio.getText().equals("")){JOptionPane.showMessageDialog(this, "la casilla del folio esta vacia");
        }
        else{
           cDao.eliminar(folioElim);
           JOptionPane.showMessageDialog(this, "SE ELIMINO EL REGISTRO DE CITA"+folioElim);
        }
        dispose();
    }
    void eliminarCliente(){
        if(txtFolio.getText().equals("")){JOptionPane.showMessageDialog(this, "la casilla del folio esta vacia");
        }
        else{
           dao.eliminar(idCli);
           JOptionPane.showMessageDialog(this, "SE ELIMINO EL REGISTRO DEL ClIENTE"+idCli);
        }
        dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIndicador = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lbIndicador.setFont(new java.awt.Font("Marion", 1, 16)); // NOI18N
        lbIndicador.setText("FOLIO DE CITA :");

        txtFolio.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 17)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Marion", 1, 16)); // NOI18N
        jLabel3.setText("¿ESTA SEGURO QUE DESEA ELIMINAR LOS REGISTROS?");

        jButton1.setText("SI");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("NO");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lbIndicador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIndicador)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(folioElim!=0){eliminarCita();}
        if(idCli!=0){eliminarCliente();}
    }//GEN-LAST:event_jButton1MouseClicked

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        
        if(folioElim!=0){lbIndicador.setText("FOLIO DE CITA: ");
        txtFolio.setText(""+folioElim);
        }
        if(idCli!=0){lbIndicador.setText("ID CLIENTE: ");
        txtFolio.setText(""+idCli);
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbIndicador;
    private javax.swing.JTextField txtFolio;
    // End of variables declaration//GEN-END:variables
}
